language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"
install:
    - pip install .[test]
script:
    pytest --cov-report= --cov=zeroscale tests/
after_success:
    coveralls
